const IPC_CHANNELS = {
  NAV_GO: 'NAV_GO',
  NAV_BACK: 'NAV_BACK',
  NAV_FORWARD: 'NAV_FORWARD',
  NAV_RELOAD: 'NAV_RELOAD',
  QUEUE_ADD_CURRENT: 'QUEUE_ADD_CURRENT',
  QUEUE_GET_ALL: 'QUEUE_GET_ALL',
  QUEUE_SET_CHECKED: 'QUEUE_SET_CHECKED',
  QUEUE_REMOVE_SELECTED: 'QUEUE_REMOVE_SELECTED',
  QUEUE_CLEAR: 'QUEUE_CLEAR',
  SETTINGS_GET: 'SETTINGS_GET',
  SETTINGS_SET_OUTPUT_DIR: 'SETTINGS_SET_OUTPUT_DIR',
  SETTINGS_SET_FORMATS: 'SETTINGS_SET_FORMATS',
  EXPORT_RUN_SELECTED: 'EXPORT_RUN_SELECTED',
  EXPORT_PROGRESS: 'EXPORT_PROGRESS',
  EXPORT_DONE: 'EXPORT_DONE',
};

module.exports = {
  IPC_CHANNELS,
};
